services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Revive
      POSTGRES_DB: db_3
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
      PGADMIN_DEFAULT_PASSWORD: Revive
    ports:
      - "5050:80"
    depends_on:
      - db

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/my_database
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
